# Generated by Django 2.1.8 on 2019-04-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('status', models.BooleanField(choices=[(True, 'Present'), (False, 'Absent')])),
            ],
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='classSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(max_length=10, verbose_name='Day of Week')),
                ('DayNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.DateField()),
                ('Salary', models.IntegerField(verbose_name='Monthly Salary')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtainedMarks', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarks', models.IntegerField()),
                ('weightage', models.IntegerField()),
                ('Name', models.CharField(max_length=12)),
                ('classSectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.classSection')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('startTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('periodNumber', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=20, verbose_name='Last Name')),
                ('FatherName', models.CharField(max_length=30, verbose_name='Father Name')),
                ('Cnic', models.CharField(max_length=20, verbose_name='CNIC/B-FORM')),
                ('Address', models.CharField(max_length=50, verbose_name='Permenant Address')),
                ('Contact', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Lookup')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='Program Name')),
                ('EntryTest', models.DateField(verbose_name='Entry Test')),
                ('MeritList', models.DateField(verbose_name='Mert List')),
                ('FeeSubmission', models.DateField(verbose_name='Fee Submission')),
                ('ClassesCommence', models.DateField(verbose_name='Class Starts')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minRange', models.IntegerField()),
                ('maxRange', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('ExamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Exam')),
                ('classSectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.classSection')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionName', models.CharField(max_length=20, verbose_name='Section')),
                ('Strength', models.IntegerField()),
                ('ClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Subject')),
                ('TeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Employee')),
                ('classSectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.classSection')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchedualeDateAndTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Calender')),
                ('SchedualeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Scheduale')),
                ('SubjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Subject')),
                ('TeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Employee')),
                ('periodNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Period')),
            ],
        ),
        migrations.AddField(
            model_name='scheduale',
            name='SubjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Subject'),
        ),
        migrations.AddField(
            model_name='scheduale',
            name='dayName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Days'),
        ),
        migrations.AddField(
            model_name='scheduale',
            name='periodNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Period'),
        ),
        migrations.AddField(
            model_name='fine',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Lookup'),
        ),
        migrations.AddField(
            model_name='fine',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Person'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='Result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Result'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Lookup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Person'),
        ),
        migrations.AddField(
            model_name='department',
            name='InstitueId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Institue'),
        ),
        migrations.AddField(
            model_name='department',
            name='ProgramId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Program'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='SectionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Section'),
        ),
        migrations.AddField(
            model_name='class',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department'),
        ),
        migrations.AddField(
            model_name='calender',
            name='DayName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Days'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='designaion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Lookup'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('classSectionId', 'TeacherId', 'SubjectId')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('SectionName', 'ClassId')},
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('ClassId', 'SectionId')},
        ),
    ]
