# Generated by Django 2.1.8 on 2019-04-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=12)),
                ('monthlyFee', models.IntegerField()),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department')),
                ('classSectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.classSection')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='StudentId',
            field=models.ForeignKey(default=198, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Student'),
            preserve_default=False,
        ),
    ]
