# Generated by Django 2.1.8 on 2019-04-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_auto_20190414_1405'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='exam',
            name='endTime',
            field=models.DateTimeField(default='2019-10-03 10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='startTime',
            field=models.DateTimeField(default='2019-10-03 11:00'),
            preserve_default=False,
        ),
    ]
