# Generated by Django 2.1.8 on 2019-04-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_auto_20190414_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Sub_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Subject'),
            preserve_default=False,
        ),
    ]
