# Generated by Django 2.1.8 on 2019-04-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_exam_sub_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Sub_Id',
            new_name='Subject_Id',
        ),
    ]
