# Generated by Django 2.1.8 on 2019-04-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_auto_20190414_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='DepartmentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='registered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='ProgramId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Program'),
            preserve_default=False,
        ),
    ]
