# Generated by Django 2.1.8 on 2019-04-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_auto_20190415_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='ProgramId',
        ),
        migrations.AddField(
            model_name='program',
            name='DepartmentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department'),
            preserve_default=False,
        ),
    ]
