# Generated by Django 2.1.8 on 2019-04-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0010_class_programid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ClassId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SectionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Section'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='classSectionId',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('ClassId', 'SectionId')},
        ),
    ]
