# Generated by Django 2.1.8 on 2019-04-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0011_auto_20190427_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
