# Generated by Django 2.1.8 on 2019-04-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_auto_20190427_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PersonId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Person'),
            preserve_default=False,
        ),
    ]
