# Generated by Django 2.1.8 on 2019-04-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0014_student_personid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Cnic',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNIC/B-FORM'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='PersonId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Person', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='SectionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registrationNumber',
            field=models.CharField(max_length=12, unique=True, verbose_name='Registration Number'),
        ),
    ]
