# Generated by Django 2.1.8 on 2019-04-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0015_auto_20190429_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='registered',
        ),
        migrations.AddField(
            model_name='section',
            name='ProgramId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Program', verbose_name='Program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='ClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='section',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department', verbose_name='Department'),
        ),
    ]
