# Generated by Django 2.1.8 on 2019-04-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0016_auto_20190429_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ProgramId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Program', verbose_name='Program'),
            preserve_default=False,
        ),
    ]
