# Generated by Django 2.1.8 on 2019-05-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0017_student_programid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='ProgramId',
        ),
        migrations.AddField(
            model_name='subject',
            name='DepartmentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department'),
            preserve_default=False,
        ),
    ]
