# Generated by Django 2.1.8 on 2019-05-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0018_auto_20190503_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SemsterName', models.CharField(max_length=10)),
                ('ClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department')),
                ('ProgramId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Program')),
                ('SubjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Subject')),
            ],
        ),
    ]
