# Generated by Django 2.1.8 on 2019-05-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0021_auto_20190504_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='designaion',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='personId',
        ),
        migrations.AddField(
            model_name='attendance',
            name='StudentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='SubjectId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calender',
            name='date_Time',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
