# Generated by Django 2.1.8 on 2019-05-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0022_auto_20190504_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(),
        ),
    ]
