# Generated by Django 2.1.8 on 2019-05-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0024_auto_20190505_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Batch',
        ),
        migrations.AlterField(
            model_name='employee',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Designation',
            field=models.IntegerField(choices=[(1, 'Chair Person'), (2, 'Associate Professor'), (3, 'Asistant Professor'), (4, 'Professor'), (5, 'Clerk')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Person', verbose_name='Person'),
        ),
    ]
