# Generated by Django 2.1.8 on 2019-05-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0025_auto_20190506_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Subject_Id',
            new_name='SubjectId',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='classSectionId',
        ),
        migrations.AddField(
            model_name='exam',
            name='ClassId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='DepartmentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='SectionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Section'),
            preserve_default=False,
        ),
    ]
