# Generated by Django 2.1.8 on 2019-05-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0026_auto_20190506_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacher',
            name='SectionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminApp.Section'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subjectteacher',
            name='classSectionId',
        ),
    ]
