# Generated by Django 2.1.8 on 2019-05-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0028_auto_20190508_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='ClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='ProgramId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='SubjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Subject', verbose_name='Subject'),
        ),
    ]
