# Generated by Django 2.1.8 on 2019-05-09 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0030_auto_20190509_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SectionId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Section', verbose_name='Section'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('ExamId', 'StudentId')},
        ),
    ]
