# Generated by Django 2.1.8 on 2019-05-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0032_auto_20190509_0503'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
    ]
