# Generated by Django 2.1.8 on 2019-05-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0033_auto_20190509_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Person', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='SectionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.Section', verbose_name='Section'),
        ),
    ]
